### ISSUE TITLE
Nested dict fails.

### ISSUE THREAD

**Issue by Bennyelg** [numberly/thingy#13]
```python
pd = Thingy({"name": {"st": "benny"}, "lastname": "Elgazar"})
pd.name.st
```
```AttributeError: 'dict' object has no attribute 'st'```

**Comment by ramnes** [comment]
Hello @Bennyelg,

Thank you for opening this issue! Although, "it's not a bug, it's a feature". :wink: 

Automatically casting nested dictionaries is not part of our plans for Thingy. The main goal of Thingy is to allow the creation of classes that can be easily coerced from dictionaries, not to replace dictionaries on every use-cases. See [Mongo-Thingy](https://github.com/numberly/mongo-thingy) for a good example of why we created Thingy.

Some other libraries might suit your needs better; on top of my head there are [Addict](https://github.com/mewwts/addict) and [DotMap](https://github.com/drgrib/dotmap) that use that kind of behavior you're looking for, and that really aim to completely replace `dict`.

Do you have a particular reason to use Thingy rather than those two?
